package com.calyrsoft.ucbp1.features.dollar.data.mapper

import com.calyrsoft.ucbp1.features.dollar.data.database.entity.DollarEntity
import com.calyrsoft.ucbp1.features.dollar.domain.model.DollarModel

fun DollarEntity.toModel(): DollarModel {
    return DollarModel(
        dollarOfficial = this.dollarOfficial,
        dollarParalelo = this.dollarParalelo,
        dollarUSDT = this.dollarUSDT,
        dollarUSDC = this.dollarUSDC,
        timestamp = this.timestamp
    )
}

fun DollarModel.toEntity(): DollarEntity {
    return DollarEntity(
        // The ID is auto-generated by Room, so it's not needed here
        // We'll let Room handle it.
        dollarOfficial = this.dollarOfficial,
        dollarParalelo = this.dollarParalelo,
        dollarUSDT = this.dollarUSDT,
        dollarUSDC = this.dollarUSDC,
        timestamp = this.timestamp
    )
}